# Generated by Django 5.0 on 2024-01-03 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0008_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(default=datetime.date(2024, 1, 3)),
        ),
    ]
