# Generated by Django 5.0 on 2024-01-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_alter_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
